version: 2.1
jobs:
  build_test_deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install and configure gcloud
          command: |
            curl https://sdk.cloud.google.com > install.sh
            bash install.sh --disable-prompts
            source $HOME/google-cloud-sdk/path.bash.inc
            gcloud components update kubectl
            echo "$GCLOUD_SERVICE_KEY" >> service-account.json
            gcloud auth activate-service-account --key-file service-account.json
            gcloud config set project k8s-deployment-382006
            gcloud config set compute/zone europe-west1-b
            gcloud container clusters get-credentials cluster

      - run:
          name: run unit test
          command: |
            docker build -t qassimov/react-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true qassimov/react-test npm test
      - run:
          name: login to docker hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - deploy:
          name: build, push and update k8s cluster images
          command: |
            chmod +x deploy.sh
            ./deploy.sh

workflows:
  cicd:
    jobs:
      - build_test_deploy
